In [1]:
import numpy as np
import tensorflow as tf

dataPhase = np.load("trainLenetdataPhase.npy")
dataMag = np.load("trainLenetdataMag.npy")
dataY = np.load("trainLenetdataY.npy")


/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
from keras.models import Sequential
from keras.layers import Convolution2D
model = Sequential()
model.add(Convolution2D(filters=6,kernel_size=(5,5),strides=1,activation='relu',input_shape=(32,32,1)))

Using TensorFlow backend.


In [3]:
from keras.layers import MaxPooling2D
model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))
model.add(Convolution2D(filters=16,kernel_size=(5,5),strides=1,activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))

In [4]:
from keras.layers import Flatten
model.add(Flatten())

In [5]:
from keras.layers import Dense
model.add(Dense(120,input_shape=(400,),activation='relu'))
model.add(Dense(84,activation='relu'))
model.add(Dense(20,activation='softmax'))

In [6]:
from keras.optimizers import Adam
optimizer = Adam(lr=0.0001)
model.compile(loss='categorical_crossentropy',optimizer=optimizer,metrics=['accuracy'])

In [7]:
print(dataY.shape)
print(dataMag.shape)
print(dataY)
#print(dataMag)
#print(dataPhase)
#print(dataMag)

(21596, 20)
(21596, 32, 32, 1)
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 28, 28, 6)         156       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 6)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 10, 10, 16)        2416      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 5, 5, 16)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 400)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 120)               48120     
_________________________________________________________________
dense_2 (Dense)              (None, 84)                10164     
__________

In [9]:
model.fit(x=dataMag,y=dataY,epochs=20,batch_size=32)

Epoch 1/20
21596/21596 [==============================] - 24s 1ms/step - loss: 1.2903 - acc: 0.6427
Epoch 2/20
21596/21596 [==============================] - 21s 975us/step - loss: 0.3800 - acc: 0.9027
Epoch 3/20
21596/21596 [==============================] - 22s 998us/step - loss: 0.2390 - acc: 0.9349
Epoch 4/20
21596/21596 [==============================] - ETA: 0s - loss: 0.1782 - acc: 0.950 - 23s 1ms/step - loss: 0.1791 - acc: 0.9501
Epoch 5/20
21596/21596 [==============================] - 23s 1ms/step - loss: 0.1442 - acc: 0.9585
Epoch 6/20
21596/21596 [==============================] - 21s 995us/step - loss: 0.1167 - acc: 0.9656
Epoch 7/20
21596/21596 [==============================] - 22s 1ms/step - loss: 0.1048 - acc: 0.9688
Epoch 8/20
21596/21596 [==============================] - 21s 958us/step - loss: 0.0913 - acc: 0.9748
Epoch 9/20
21596/21596 [==============================] - 24s 1ms/step - loss: 0.0806 - acc: 0.9764
Epoch 10/20
21596/21596 [=============================

In [11]:
#model.save('Lenet_model_with_Mag.h5') 
model.save('Lenet_model_with_overlap16_turkey_Mag.h5') 

[8.19692403e-08 9.36005440e-12 1.59889246e-13 4.57460902e-10
 9.99854445e-01 1.11907306e-11 4.28089379e-06 9.00322557e-05
 4.19141486e-07 4.65972573e-12 2.63611919e-12 2.04748758e-05
 3.50775697e-09 1.11668765e-10 2.43203097e-11 2.67762116e-05
 1.51102512e-14 3.02982085e-06 4.44321586e-07 2.63753519e-10]


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
